project:
  type: website
  output-dir: ../docs
  render:
    - index.qmd
    - 005_setup.qmd
    - 01_introduction_to_r.qmd
    - 02_editors.qmd
    - 03_data_frames.qmd
    - 04_data_wrangling.qmd
    - 05_grammar_of_graphics.qmd
    - 10_git.qmd
    - 20_basic_principles.qmd
    - 21_statistical_philosophies.qmd
    - 22_estimation.qmd
    - 30_glm.qmd
    - 35_bayesian_linear_models.qmd
    - 40_synthetic_world.qmd
    - 42_data_preparation.qmd

website:
  title: ReefCloud R/Statistics resources
  sidebar:
    background: primary
    logo: "https://reefcloud.ai/static/media/coreLogoName.04eb209b6a92259208f9d8edb621bc4c.svg"
    pinned: true
    align: center
    style: docked
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
        icon: house
      - href: 005_setup.qmd
        text: Setup
        icon: house
      - text: "---"
      - section: R basics
        contents:
        - href: 01_introduction_to_r.qmd
          text: Introduction to R
          icon: house
        - href: 02_editors.qmd
          text: Code editors
          icon: house
        - href: 03_data_frames.qmd
          text: Data frames
          icon: house
        - href: 04_data_wrangling.qmd
          text: Data wrangling
          icon: house
        - href: 05_grammar_of_graphics.qmd
          text: The grammar of graphics
          icon: house
      - section: Reproducible research
        contents:
        - href: 10_git.qmd
          text: Introduction to git
          icon: house
      - section: Statistical principles
        contents:
        - href: 20_basic_principles.qmd
          text: Basic principles
          icon: house
        - href: 21_statistical_philosophies.qmd
          text: Statistical philosophies
          icon: house
        - href: 22_estimation.qmd
          text: Estimation and inference
          icon: house
      - section: Introduction to linear modelling
        contents:
        - href: 30_glm.qmd
          text: Generalised linear models
          icon: house
        - href: 35_bayesian_linear_models.qmd
          text: Bayesian linear models
          icon: house
      - section: Analyses
        contents:
        - href: 40_synthetic_world.qmd
          text: Synthetic world and data
          icon: house
        - href: 42_data_preparation.qmd
          text: Data preparation
          icon: house

format:
  html:
    theme: [default, resources/tut-style.scss]
    css: resources/tut-style.css
    toc: true
    page-layout: full
    ## Code
    code-fold: false
    code-tools: true
    code-summary: "Show the code"
    code-line-numbers: true
    code-block-border-left: "#ccc"
    code-copy: true
    highlight-style: atom-one
    number-sections: true
    number-depth: 3

execute:
  freeze: auto