name: Render and publish the tutorials

on:
  workflow_dispatch:
#  pull_request:
#  push:
#    branches: ['release']

jobs:
  render-tutorials:
    runs-on: ubuntu-latest

    name: ${{ matrix.config.r }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - { r: '4.3.2' }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # install R
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.R }}

      ## Install R packages
      - name: install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages: |
            any::rmarkdown
            any::magick
            any::pdftools
            any::quarto
            any::tidyverse
            any::mvabund
            any::pander
            any::GGally

      - name: install tinytex
        uses: r-lib/actions/setup-tinytex@v2
      - run: tlmgr --version

      - name: Install additional LaTeX packages
        run: |
          tlmgr install titlesec
          tlmgr list --only-installed

      - name: Install Google Fonts
        run: |
          wget -O architects_daughter.zip https://fonts.google.com/download?family=Architects%20Daughter
          unzip -d architects_daughter/ architects_daughter.zip
          mv architects_daughter /usr/share/fonts/
          wget -O inconsolata.zip https://fonts.google.com/download?family=Inconsolata
          unzip -d inconsolata/ inconsolata.zip
          mv inconsolata /usr/share/fonts/
          fc-cache -fv
          #fc-list
          #fc-list -v | grep -i archi
          fc-list -v | grep -i inconsolata

      # install quarto
      - name: Install quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Change ImageMagick policy to allow pdf->png conversion.
        run: |
          sudo sed -i 's/^.*policy.*coder.*none.*PDF.*//' /etc/ImageMagick-6/policy.xml
          
      # Checkout the gh-pages branch into the docs folder    
      - name: retrieve previous compiled pages
        uses: actions/checkout@v3
        with:
          path: doc  # Specify the target folder for checkout
          ref: gh-pages  
      - name: check that the docs folder is there and populated
        run: | 
          ls -la
          ls -la doc
      # render tutorials
      - name: Make tutorials
        #run: make -i tut
        run: |
          echo "library(quarto); quarto_render(\"tut/index.qmd\")" | R --no-save --no-restore;
          echo "library(quarto); quarto_render(\"tut/10_git.qmd\")" | R --no-save --no-restore;

        
      # Deploy site to gh-pages branch
      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@4.1.4
      #   with:
      #     branch: gh-pages
      #     folder: docs
